### ISSUE TITLE
Difference between uref and u

### ISSUE THREAD

**Issue by cyndyfem** [mjucker/aostools#7]
Hi,
Thanks for developing this awesome tool.

I would like to ask,
Please, what is the difference between uref and u when using the ComputeWaveActivityFlux function?
Since there are no tutorials on it yet, please, could you clarify this?
I have monthly u and v wind datasets. Please, see my code below.

data = xr.open_dataset(data1)
lon=data['lon']
lat=data['lat']
u = data['uwnd']
v = data['vwnd']
pres = data['level']
tref = data['air'] + 273.15 ##must be in Kelvin
hgt = data['hgt']

WAF = cli.ComputeWaveActivityFlux(phi_or_u = u,phiref_or_v = v,uref=u,vref=v,lat='infer',lon='infer',pres='infer',tref=tref,is_anomaly=False,qg=False,use_windspharm=False)

Thank you

**Comment by cyndyfem** [comment]
Just to add that I am working on a global file.  All outputs returned zero.

**Comment by mjucker** [comment]
Hi @cyndyfem . You will have to go through the theory for this. uref is the wind field through which the waves are propagating, and u-uref is the anomaly field describing the waves. 
Note also that you will not get anything meaningful with monthly data, as the theory is based on instantaneous covariances.
I am closing this as it does not seem to be a coding issue, but rather a physical issue.
